---
- name: "A simple playbook"
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  become_method: "ansible.builtin.sudo"
  tasks:
    - name: "Create a file with some information on our host"
      ansible.builtin.copy:
        dest: "/home/ansible/info.txt"
        mode: "0444"
        owner: ansible
        group: ansible
        content: "This was run on {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"

  roles:
    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - cowsay
